export const EDIT_TIME = 'EDIT_TIME'
export const SAVE_EDIT = 'SAVE_EDIT'
export const CANCEL_EDIT_TIME = 'CANCEL_EDIT_TIME'
export const SET_TEXT = 'SET_TEXT'
export const SET_TIME = 'SET_TIME'
export const SET_DAYS = 'SET_DAYS'
export const SET_DAY = 'SET_DAY'
export const SET_COLUMN = 'SET_COLUMN'